Website=https://tutorialsninja.com/demo/
driverlink=firefox
Firstnameforregister=Ramesh
Lastforregister=Abdul
Telephoneforregister=1245678930
Validpasswordforregister=Mickymouse@1245
Validpasswordconfirmforregister=Mickymouse@1245
Login_validusername=ghkjhblkjhkjhh@gmail.com
Login_validpassword=Candyjai@22
Login_invalidpassword=12345
excelFilePath=\\src\\test\\resources\\Tutorialsninjaupdate.xlsx
extentReportPath=\\target\\reports\\TNExtentReport.html
screenshotsPath=\\target\\Screenshot\\